name: Reuse other workflow
on: 
  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: '@jvertos'
  use-output:
    needs: call-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Output
        run: echo "It ran ${{ needs.call-workflow.outputs.current-time }}"
